### ISSUE TITLE
Website support framework

### ISSUE THREAD

**Issue by rafalohaki** [creativetimofficial/black-dashboard-flask#1]
Is it possible to support one of these frameworks?
https://github.com/Neoteroi/BlackSheep
https://github.com/klen/muffin
https://github.com/sanic-org/sanic/

thanks

**Comment by app-generator** [comment]
Hello @rafalohaki! 

Ty for using our products! 
Regarding `async support`, FASTapi is the first one on the list (separate seed).

For now, async support is not scheduled on the product ROADMAP. 

Let us know if we can help you with anything else. 
BR
